# Generated by Django 2.2.9 on 2020-01-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseClassification',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_standard', models.CharField(max_length=6)),
                ('category_code', models.CharField(max_length=3)),
                ('diagnosis_code', models.CharField(max_length=4)),
                ('full_code', models.CharField(max_length=7, unique=True)),
                ('abbreviated_description', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=100)),
                ('category_title', models.CharField(max_length=80)),
            ],
        ),
    ]
