# Generated by Django 2.2.9 on 2020-01-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseclassification',
            name='category_code',
            field=models.CharField(max_length=4),
        ),
    ]
