# Generated by Django 2.2.9 on 2020-01-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200130_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseclassification',
            name='diagnosis_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
