# Generated by Django 2.2.9 on 2020-01-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200130_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseclassification',
            name='abbreviated_description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='diseaseclassification',
            name='category_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diseaseclassification',
            name='full_description',
            field=models.CharField(max_length=255),
        ),
    ]
